### PR TITLE
Autocomplete methods and functions

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hey all, hey @imagejan, hey @ctrueden,

I'm testing the autocompletion of variable names and functions+comments for some time. Also users on the forum seemed to be pretty happy about it. 
https://forum.image.sc/t/auto-code-completion-for-ij-macro/11642/95

Do you see any issues? Shall we merge it? Thanks!

Cheers,
Robert

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Hey @ctrueden 

are there any news regarding the CI?

I added some more updates and new content to the auto-completion. For example @imagejan  may like this one: 
image

Thanks for your support!

Cheers,
Robert

**Comment by ctrueden** [comment]
I force-pushed a change that I hope will fix it.

**Comment by ctrueden** [comment]
Here is the patch that I squashed in:
```diff
diff --git src/main/java/net/imagej/legacy/IJ1Helper.java src/main/java/net/imagej/legacy/IJ1Helper.java
index 41ee03b..4919c4e 100644
--- src/main/java/net/imagej/legacy/IJ1Helper.java
+++ src/main/java/net/imagej/legacy/IJ1Helper.java
@@ -598,6 +598,11 @@ public class IJ1Helper extends AbstractContextual {
                return Interpreter.getInstance();
        }

+       /** Gets the result of {@link Interpreter#getAdditionalFunctions()}. */
+       public static String getAdditionalMacroFunctions() {
+               return Interpreter.getAdditionalFunctions();
+       }
+
        /**
         * Gets the value of the specified variable, from the given macro
         * {@link Interpreter}.
diff --git src/main/java/net/imagej/legacy/plugin/MacroAutoCompletionProvider.java src/main/java/net/imagej/legacy/plugin/MacroAutoCompletionProvider.java
index 760d3c5..4ee4ff2 100644
--- src/main/java/net/imagej/legacy/plugin/MacroAutoCompletionProvider.java
+++ src/main/java/net/imagej/legacy/plugin/MacroAutoCompletionProvider.java
@@ -42,14 +42,14 @@ import java.util.ArrayList;
 import java.util.Collections;
 import java.util.List;

-import ij.macro.Interpreter;
+import net.imagej.legacy.IJ1Helper;
+
 import org.fife.ui.autocomplete.BasicCompletion;
 import org.fife.ui.autocomplete.Completion;
 import org.fife.ui.autocomplete.DefaultCompletionProvider;
 import org.fife.ui.autocomplete.SortByRelevanceComparator;
 import org.fife.ui.rtextarea.RTextArea;
 import org.fife.ui.rtextarea.ToolTipSupplier;
-
 import org.scijava.module.ModuleInfo;
 import org.scijava.module.ModuleService;

@@ -324,7 +324,7 @@ class MacroAutoCompletionProvider extends DefaultCompletionProvider implements
                        e.printStackTrace();
                        return;
                }
-               text = text + "\n" + Interpreter.getAdditionalFunctions();
+               text = text + "\n" + IJ1Helper.getAdditionalMacroFunctions();

                int linecount = 0;
                String[] textArray = text.split("\n");
```

**Comment by ctrueden** [comment]
The CI passed, so I merged it.

**Comment by haesleinhuepf** [comment]
Great, thanks @ctrueden ! 😍

**Pull request merged**
