### PR TITLE
Support RoiManager as parameter input

### PR DESCRIPTION
**Pull request by imagejan**
Modeled after https://github.com/imagej/imagej-legacy/commit/7af335206959912fefa5ddd9c83258270bbbfa42.

(Thanks, @ctrueden!)

### CODE REVIEW

**Comment by imagejan** [comment]
I see that Travis fails with
```
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at net.imagej.legacy.plugin.RoiManagerPreprocessorTest.testRoiManagerParameter(RoiManagerPreprocessorTest.java:71)
```

probably because RoiManager is not patched to be headless compatible, right?

**Comment by ctrueden** [comment]
Great!

The test failure is indeed due to #153. For now, we will need to add `assumeTrue(!GraphicsEnvironment.isHeadless());` to the beginning of that test, so it does not run on Travis.

**Comment by imagejan** [comment]
Alright, Travis is happy now 😄

**Comment by ctrueden** [comment]
Thanks!

**Pull request merged**
