### PR TITLE
Implement IJ1 macro autocompletion

### PR DESCRIPTION
**Pull request by ctrueden**
Continuation of scijava/script-editor#21.

### CODE REVIEW

**Comment by ctrueden** [comment]
The autocompletion of functions from `functions.html` is working on my system. However, the items from `functions_extd.html` are not working. Can others comment on whether they are working? @haesleinhuepf were they confirmed to work on your system before I migrated the patches here?

**Comment by haesleinhuepf** [comment]
They are still working on my system. 

Try by entering `w`, hit CTRL (CMD? on mac) + SPACE and check if `while...` shows up in the pullown.
image

**Comment by frauzufall** [comment]
I get `if` and `while` autocompletions on Xubuntu 17.10.

**Comment by haesleinhuepf** [comment]
Shall we merge?

Btw.: Thanks for the support!  ❤

**Comment by ctrueden** [comment]
Thanks for your efforts, @haesleinhuepf! Thanks for testing, everyone!

**Pull request merged**
