### PR TITLE
Legacy dataset service

### PR DESCRIPTION
**Pull request by bnorthan**
`LegacyDatasetService` overrides `getDatasets()` such that all `ImageDisplays` will be lazily registered when the user calls `getDatasets()`.  All other methods simply wrap a call to the next highest priority `DatasetService`.

LegacyDatasetService follows the pattern used for [LegacyImageDisplayService](../blob/master/src/main/java/net/imagej/legacy/display/LegacyImageDisplayService.java).

@ctrueden, @hinerm the code that registers the datasets is in the function `registerDatasets()`.  Let me know if that look OK.  

My understanding is that this service will be made obsolete by #105.  If that is not the case let me know.  If this code has a long-term shelf life than there is a couple more things I should do (like putting similar code for `LegacyDatasetService` and `LegacyImageDisplayService` in a shared utility).

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks for following up with this, @bnorthan. There are some tweaks I'd like to do with the patches; I'll try to work on it next week some time.

**Comment by imagejan** [comment]
@ctrueden is this PR still relevant?

**Comment by ctrueden** [comment]
Thanks for the ping. I cannot remember. I will bookmark this too look at again soon, by some definition of "soon."

**Comment by ctrueden** [comment]
By the definition of "soon" where it is one year and two days later: I now close this, since #182 was merged. If anyone has reason to think these changes are still necessary, please reopen and/or file another PR accordingly.

**Pull request closed without merging**
