### PR TITLE
fixing two null pointer exceptions in case the IJ1Helper is not set

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hey guys,

related to the issue I posted on the forum:
https://forum.image.sc/t/imagej2-convert-imageplus-to-dataset/20728

For whatever reason (I really would like to know), the IJ1Helper is not set in the legacy service. The resulting NullPointerExceptions prevent me from working. That's why I'm suggesting this bugfix. If anybody has an idea when/why this IJ1Helper is not set, please let me know!

Cheers,
Rober

### CODE REVIEW

**Comment by ctrueden** [comment]
@haesleinhuepf I pushed it. Could you please pull this branch, test it, and let me know if it still solves your issue? If it does, and you notice no other issues, I will merge it in time for the next release!

**Comment by haesleinhuepf** [comment]
Hey @ctrueden ,

you were right, the issue is that there might be several ImageJ instances. I tested it in a minimal bug reproducing example:
https://github.com/haesleinhuepf/ImagePlusToDataset/blob/master/src/main/java/imageplustodataset/ImagePlusToDataset.java

The fix works. However, we get a new issue: `legacyService.getImageMap()` is null: 
https://github.com/imagej/imagej-legacy/blob/master/src/main/java/net/imagej/legacy/display/LegacyImageDisplayViewer.java#L126

The full error message is:
```
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:118)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:193)
	at org.scijava.ui.AbstractUserInterface.show(AbstractUserInterface.java:106)
	at org.scijava.ui.UserInterface.show(UserInterface.java:78)
	at org.scijava.ui.DefaultUIService.show(DefaultUIService.java:238)
	at imageplustodataset.ImagePlusToDataset.main(ImagePlusToDataset.java:32)
Caused by: java.lang.NullPointerException
	at net.imagej.legacy.display.LegacyImageDisplayViewer.view(LegacyImageDisplayViewer.java:134)
	at net.imagej.legacy.display.LegacyImageDisplayViewer.view(LegacyImageDisplayViewer.java:102)
	at net.imagej.legacy.ui.LegacyUI$1.run(LegacyUI.java:197)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:301)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I'm not sure what to do when there is no way to lookup or create a display... What do you think about making legacyService a singleton or IJ1Helper? All instances of net.imagej.ImageJ would then access the same helper... It may screw up independence between ImageJ instances.

I'm in parallel cleaning up our code base to remove parallel existing instances of ImageJ... But nevertheless, would be nice if this would work in general.

**Comment by ctrueden** [comment]
Making the `LegacyService` + `IJ1Helper` fully work across multiple SciJava contexts would be a significant undertaking.

Currently, there is a one-to-one correspondence between the `ij.ImageJ` application instance and the `org.scijava.Context` that spawned it. It would break the aforementioned `IJ.runPlugIn("org.scijava.Context", "")` code if we changed the system such that multiple `org.scijava.Context` objects all shared one singleton `IJ1Helper`. Which one of the multiple contexts should the `IJ.runPlugIn` call then return?

Furthermore, the `net.imagej.display.ImageDisplay` is a `Contextual` object, meaning it is associated with one and only one `Context`. If there are multiple SciJava contexts, with which one(s) would `ij.ImagePlus` instances be synced? Would we create/sync one `ImageDisplay` per `Context`?

You are welcome to explore strategies for enabling multiple simultaneous contexts with fully functional `LegacyService`, but it is a deep change to the system. Expect substantial obstacles. Your best bet, from a pragmatic standpoint, is to eliminate construction of additional contexts, in favor of reuse of the one primary one.

**Comment by haesleinhuepf** [comment]
Great. I just tested in detail and it works nicely! Thanks again @ctrueden for your instant support!

**Pull request merged**
